## Imports

In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
import tensorflow as tf
from tensorflow import keras

## Scikit-Learn Perceptron

In [2]:
iris = load_iris()
X = iris.data[:, (2, 3)] #only selecting petal length and width features
y = (iris.target==0).astype(np.int)

per_clf = Perceptron()
per_clf.fit(X, y)

y_pred = per_clf.predict([[2, 0.5], [1.4, 0.2]])
y_pred

array([0, 1])

## Keras - Fashion MNIST
###  Load data

In [3]:
fashion_mnist = keras.datasets.fashion_mnist
(X_train_full, y_train_full), (X_test, y_test) = fashion_mnist.load_data()

X_valid, X_train = X_train_full[:5000]/255, X_train_full[5000:]/255
y_valid, y_train = y_train_full[:5000], y_train_full[5000:]

class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle Boot']


### Build the Neural Network

In [4]:
model = keras.models.Sequential()
model.add(keras.layers.Flatten(input_shape=[28, 28]))
model.add(keras.layers.Dense(300, activation="relu"))
model.add(keras.layers.Dense(100, activation="relu"))
model.add(keras.layers.Dense(10, activation="softmax"))

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 300)               235500    
_________________________________________________________________
dense_1 (Dense)              (None, 100)               30100     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1010      
Total params: 266,610
Trainable params: 266,610
Non-trainable params: 0
_________________________________________________________________


### Accessing a model's layers

In [6]:
model.layers

#### Layer names

In [7]:
[x.name for x in model.layers]

['flatten', 'dense', 'dense_1', 'dense_2']

#### Fetching a layer by its index

In [8]:
hidden_1 = model.layers[1]
model.get_layer('dense') is hidden_1

True

#### Layer Parameters

In [9]:
weights, biases = hidden_1.get_weights()

In [10]:
weights

array([[ 0.05928101,  0.0346683 , -0.0628988 , ...,  0.03896258,
         0.06480795, -0.0587631 ],
       [-0.06848514, -0.07359342,  0.01454646, ...,  0.00451446,
        -0.0017158 , -0.04147208],
       [-0.0661084 ,  0.03517204,  0.03485726, ...,  0.01639731,
         0.04775663, -0.03875671],
       ...,
       [ 0.05031307, -0.06142837, -0.04709595, ...,  0.0302446 ,
        -0.06153153,  0.0324171 ],
       [ 0.00092524, -0.02505922,  0.02054995, ..., -0.04783811,
        -0.01667557, -0.0092596 ],
       [-0.00188813,  0.07011458, -0.06498121, ..., -0.01247179,
         0.03675553, -0.0160292 ]], dtype=float32)

In [11]:
biases

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

### Compiling the model

In [12]:
model.compile(loss = "sparse_categorical_crossentropy", optimizer = "sgd", metrics = ["accuracy"])

### Training and evaluating the model

In [13]:
history = model.fit(X_train, y_train, epochs = 30, validation_data = (X_valid, y_valid))

Train on 55000 samples, validate on 5000 samples
Epoch 1/30
55000/55000 [==============================] - 6s 116us/sample - loss: 0.7187 - accuracy: 0.7667 - val_loss: 0.5128 - val_accuracy: 0.8222
Epoch 2/30
55000/55000 [==============================] - 5s 91us/sample - loss: 0.4909 - accuracy: 0.8281 - val_loss: 0.4340 - val_accuracy: 0.8572
Epoch 3/30
55000/55000 [==============================] - 5s 85us/sample - loss: 0.4464 - accuracy: 0.8451 - val_loss: 0.4462 - val_accuracy: 0.8390
Epoch 4/30
55000/55000 [==============================] - 5s 89us/sample - loss: 0.4198 - accuracy: 0.8525 - val_loss: 0.4122 - val_accuracy: 0.8582
Epoch 5/30
55000/55000 [==============================] - 5s 94us/sample - loss: 0.3991 - accuracy: 0.8599 - val_loss: 0.3971 - val_accuracy: 0.8626
Epoch 6/30
55000/55000 [==============================] - 5s 100us/sample - loss: 0.3823 - accuracy: 0.8655 - val_loss: 0.3797 - val_accuracy: 0.8734
Epoch 7/30
55000/55000 [==============================]